version: '3'
services:
  key_store:
    image: fossapps/micro.keystore:1.9.1
    ports:
      - "15000:15000"
    environment:
      - ASPNETCORE_URLS=http://+:15000
      - DatabaseConfig__AutoMigrate=true
      - DatabaseConfig__Host=postgres
      - DatabaseConfig__Port=5432
      - DatabaseConfig__Name=keys
      - DatabaseConfig__User=postgres
      - DatabaseConfig__Password=postgres
    depends_on:
      - postgres
  auth:
    image: fossapps/micro.auth:2.1.2
    ports:
      - "25000:25000"
    environment:
      - ASPNETCORE_URLS=http://+:25000
      - DatabaseConfig__AutoMigrate=true
      - IdentityConfig__SignInOptions__RequireConfirmedEmail=false
      - DatabaseConfig__Host=postgres
      - DatabaseConfig__Port=5432
      - DatabaseConfig__Name=auth
      - DatabaseConfig__User=postgres
      - DatabaseConfig__Password=postgres
      - Services__KeyStore__Url=http://key_store:15000
    depends_on:
      - postgres
  app_registration:
    image: fossapps/micro.appregistration:2.0.0
    ports:
      - "35000:35000"
    environment:
      - ASPNETCORE_URLS=http://+:35000
      - DatabaseConfig__AutoMigrate=true
      - DatabaseConfig__Host=postgres
      - DatabaseConfig__Port=5432
      - DatabaseConfig__Name=app_registration
      - DatabaseConfig__User=postgres
      - DatabaseConfig__Password=postgres
      - Services__KeyStore__Url=http://key_store:15000
    depends_on:
      - postgres
  short_code_registry:
    image: smsbytes/shortcoderegistry:1.0.1
    ports:
      - "45000:45000"
    environment:
      - ASPNETCORE_URLS=http://+:45000
      - DatabaseConfig__AutoMigrate=true
      - DatabaseConfig__Host=postgres
      - DatabaseConfig__Port=5432
      - DatabaseConfig__Name=short_code_registry
      - DatabaseConfig__User=postgres
      - DatabaseConfig__Password=postgres
      - Services__KeyStore__Url=http://key_store:15000
      - Services__AppRegistration__Url=http://app_registration:35000/graphql
    depends_on:
      - postgres
  credit_management:
    image: smsbytes/creditmanagement:1.2.0
    ports:
      - "55000:55000"
    environment:
      - ASPNETCORE_URLS=http://+:55000
      - DatabaseConfig__AutoMigrate=true
      - DatabaseConfig__Host=postgres
      - DatabaseConfig__Port=5432
      - DatabaseConfig__Name=credit_management
      - DatabaseConfig__User=postgres
      - DatabaseConfig__Password=postgres
      - Services__KeyStore__Url=http://key_store:15000
    depends_on:
      - postgres
  postgres:
    image: postgres:11-alpine
    ports:
      - "15432:5432"
    volumes:
      - ./extras/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
