CREATE DATABASE auth WITH OWNER = postgres ENCODING = 'UTF8' CONNECTION LIMIT = -1;
CREATE DATABASE keys WITH OWNER = postgres ENCODING = 'UTF8' CONNECTION LIMIT = -1;
CREATE DATABASE app_registration WITH OWNER = postgres ENCODING = 'UTF8' CONNECTION LIMIT = -1;
CREATE DATABASE short_code_registry WITH OWNER = postgres ENCODING = 'UTF8' CONNECTION LIMIT = -1;
CREATE DATABASE credit_management WITH OWNER = postgres ENCODING = 'UTF8' CONNECTION LIMIT = -1;
CREATE DATABASE starter WITH OWNER = postgres ENCODING = 'UTF8' CONNECTION LIMIT = -1;
